name: Generate PDF for Textbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: |
          bundle install
      
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Install PDF tools (poppler for pdfunite)
        run: |
          sudo apt-get install -y poppler-utils

      - name: Convert HTML to PDF and merge them
        run: |
          site_folder="_site"
          output_folder="pdf_output"
          combined_pdf="textbook_full.pdf"

          mkdir -p "$output_folder"

          file_list=(
            "index.html"
            "principles/index.html"
            "principles/principles.html"
            "memory-safety/index.html"
            "memory-safety/x86.html"
            "memory-safety/vulnerabilities.html"
            "memory-safety/mitigations.html"
            "crypto/index.html"
            "crypto/intro.html"
            "crypto/symmetric.html"
            "crypto/hashes.html"
            "crypto/macs.html"
            "crypto/prng.html"
            "crypto/key-exchange.html"
            "crypto/public-key.html"
            "crypto/signatures.html"
            "crypto/certificates.html"
            "crypto/passwords.html"
            "crypto/case-studies.html"
            "crypto/bitcoin.html"
            "web/index.html"
            "web/sqli.html"
            "web/intro.html"
            "web/sop.html"
            "web/cookies.html"
            "web/csrf.html"
            "web/xss.html"
            "web/ui-attacks.html"
            "web/captchas.html"
            "network/index.html"
            "network/intro.html"
            "network/arp.html"
            "network/dhcp.html"
            "network/wpa.html"
            "network/bgp.html"
            "network/transport.html"
            "network/tls.html"
            "network/dns.html"
            "network/dnssec.html"
            "network/dos.html"
            "network/firewalls.html"
            "network/intrusion-detection.html"
            "network/abusing-intrusion-detection.html"
            "network/malware.html"
            "network/tor.html"
            "glossary.html"
          )

          for html_file in "${file_list[@]}"; do
            full_path="$site_folder/$html_file"
            output_pdf="$output_folder/$(echo "$html_file" | sed 's/\//_/g').pdf"

            echo "$output_pdf"

            if [ -f "$full_path" ]; then
              echo "Generating PDF for $html_file"
              google-chrome --headless --disable-gpu -no-pdf-header-footer --print-to-pdf="$output_pdf" "file://$PWD/$full_path"
            else
              echo "Error: File $full_path not found!" >&2
              exit 1
            fi
          done

          pdfunite \
            "pdf_output/index.html.pdf" \
            "pdf_output/principles_index.html.pdf" \
            "pdf_output/principles_principles.html.pdf" \
            "pdf_output/memory-safety_index.html.pdf" \
            "pdf_output/memory-safety_x86.html.pdf" \
            "pdf_output/memory-safety_vulnerabilities.html.pdf" \
            "pdf_output/memory-safety_mitigations.html.pdf" \
            "pdf_output/crypto_index.html.pdf" \
            "pdf_output/crypto_intro.html.pdf" \
            "pdf_output/crypto_symmetric.html.pdf" \
            "pdf_output/crypto_hashes.html.pdf" \
            "pdf_output/crypto_macs.html.pdf" \
            "pdf_output/crypto_prng.html.pdf" \
            "pdf_output/crypto_key-exchange.html.pdf" \
            "pdf_output/crypto_public-key.html.pdf" \
            "pdf_output/crypto_signatures.html.pdf" \
            "pdf_output/crypto_certificates.html.pdf" \
            "pdf_output/crypto_passwords.html.pdf" \
            "pdf_output/crypto_case-studies.html.pdf" \
            "pdf_output/crypto_bitcoin.html.pdf" \
            "pdf_output/web_index.html.pdf" \
            "pdf_output/web_sqli.html.pdf" \
            "pdf_output/web_intro.html.pdf" \
            "pdf_output/web_sop.html.pdf" \
            "pdf_output/web_cookies.html.pdf" \
            "pdf_output/web_csrf.html.pdf" \
            "pdf_output/web_xss.html.pdf" \
            "pdf_output/web_ui-attacks.html.pdf" \
            "pdf_output/web_captchas.html.pdf" \
            "pdf_output/network_index.html.pdf" \
            "pdf_output/network_intro.html.pdf" \
            "pdf_output/network_arp.html.pdf" \
            "pdf_output/network_dhcp.html.pdf" \
            "pdf_output/network_wpa.html.pdf" \
            "pdf_output/network_bgp.html.pdf" \
            "pdf_output/network_transport.html.pdf" \
            "pdf_output/network_tls.html.pdf" \
            "pdf_output/network_dns.html.pdf" \
            "pdf_output/network_dnssec.html.pdf" \
            "pdf_output/network_dos.html.pdf" \
            "pdf_output/network_firewalls.html.pdf" \
            "pdf_output/network_intrusion-detection.html.pdf" \
            "pdf_output/network_abusing-intrusion-detection.html.pdf" \
            "pdf_output/network_malware.html.pdf" \
            "pdf_output/network_tor.html.pdf" \
            "pdf_output/glossary.html.pdf" \
            "$PWD/$combined_pdf"

      - name: Upload PDF to site
        uses: actions/upload-artifact@v3
        with:
          name: textbook-full
          path: textbook_full.pdf

      - name: Commit and push changes only on push
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add textbook_full.pdf
          git commit -m "Update full PDF of textbook on site"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}