name: Generate PDF for Textbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive texlive-latex-extra poppler-utils

      - name: Generate PDFs from the textbook Markdown files
        run: |
          mkdir -p pdf_output
          
          file_list=(
            "index.md"
            "principles/index.md"
            "principles/principles.md"
            "memory-safety/index.md"
            "memory-safety/x86.md"
            "memory-safety/vulnerabilities.md"
            "memory-safety/mitigations.md"
          )
          for md_file in "${file_list[@]}"; do
            pdf_file_name="pdf_output/$(echo "$md_file" | sed 's/\//_/g').pdf"
            pandoc "$md_file" -V geometry:margin=1in --pdf-engine=pdflatex -o "$pdf_file_name"

            if [ ! -f "$pdf_file_name" ]; then
              echo "Error: PDF file $pdf_file_name not created!" >&2
              exit 1
            fi
          done
          pdfunite \
            "pdf_output/index.md.pdf" \
            "pdf_output/principles_index.md.pdf" \
            "pdf_output/principles_principles.md.pdf" \
            "pdf_output/memory-safety_index.md.pdf" \
            "pdf_output/memory-safety_x86.md.pdf" \
            "pdf_output/memory-safety_vulnerabilities.md.pdf" \
            "pdf_output/memory-safety_mitigations.md.pdf" \
            "textbook_full.pdf"

      - name: Upload PDF to site
        uses: actions/upload-artifact@v3
        with:
          name: textbook-full
          path: textbook_full.pdf

      - name: Commit and push changes only on push
        if: github.event_name == 'push'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add textbook_full.pdf
          git commit -m "Update full PDF of textbook on site"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}